module.exports = {
    GET_DIRECTORIES: "GET_DIRECTORIES",
    CHANGE_DIRECTORY: "CHANGE_DIRECTORY",
    CREATE_DIRECTORY: "CREATE_DIRECTORY",
    DELETE_DIRECTORY: "DELETE_DIRECTORY",
    FOCUS_DIRECTORY: "FOCUS_DIRECTORY",
    SHOW_ADD_DIRECTORY_MODAL: "SHOW_ADD_DIRECTORY_MODAL",
    OPEN_DIRECTORY: "OPEN_DIRECTORY",

    GET_NOTICES: "GET_NOTICES",
    CHANGE_NOTICE: "CHANGE_NOTICE",
    CREATE_NOTICE: "CREATE_NOTICE",
    DELETE_NOTICE: "DELETE_NOTICE",
    FOCUS_NOTICE: "FOCUS_NOTICE",
    OPEN_ADD_NOTICE_MODAL: "OPEN_ADD_NOTICE_MODAL",
    OPEN_NOTICE: "OPEN_NOTICE",

    SHOW_ERRORS: "SHOW_ERRORS"
};