module.exports = {
    GET_DIRECTORIES: "GET_DIRECTORIES",
    CHANGE_DIRECTORY: "CHANGE_DIRECTORY",
    CREATE_DIRECTORY: "CREATE_DIRECTORY",
    DELETE_DIRECTORY: "DELETE_DIRECTORY",

    GET_NOTICES: "GET_NOTICES",
    CHANGE_NOTICE: "CHANGE_NOTICE",
    CREATE_NOTICE: "CREATE_NOTICE",
    DELETE_NOTICE: "DELETE_NOTICE",

    SHOW_ERRORS: "SHOW_ERRORS"
};