module.exports = {
    GET_DIRECTORIES: "GET_DIRECTORIES",
    CHANGE_DIRECTORY: "CHANGE_DIRECTORY",
    CREATE_DIRECTORY: "CREATE_DIRECTORY",
    DELETE_DIRECTORY: "DELETE_DIRECTORY",
    FOCUS_DIRECTORY: "FOCUS_DIRECTORY",
    SHOW_ADD_DIRECTORY_MODAL: "SHOW_ADD_DIRECTORY_MODAL",
    EDIT_DIRECTORY: "EDIT_DIRECTORY",
    CANCEL_EDIT_DIRECTORY: "CANCEL_EDIT_DIRECTORY",
    OPEN_DIRECTORY: "OPEN_DIRECTORY",

    GET_NOTICES: "GET_NOTICES",
    CHANGE_NOTICE: "CHANGE_NOTICE",
    CREATE_NOTICE: "CREATE_NOTICE",
    DELETE_NOTICE: "DELETE_NOTICE",
    FOCUS_NOTICE: "FOCUS_NOTICE",
    EDIT_NOTICE: "EDIT_NOTICE",
    CANCEL_EDIT_NOTICE: "CANCEL_EDIT_NOTICE",
    OPEN_ADD_NOTICE_MODAL: "OPEN_ADD_NOTICE_MODAL",
    SET_NOTICES: "SET_NOTICES",

    SET_SEARCH_WORD: "SET_SEARCH_WORD",
    OPEN_SEARCH_MODAL: "OPEN_SEARCH_MODAL",
    SEARCH_NOTICES: "SEARCH_NOTICES",

    SHOW_ERRORS: "SHOW_ERRORS"
};